auto: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# markdown: rdiscount
# markdown: kramdown
highlighter: pygments
permalink: /blog/:title
paginate: 10     # 每15篇分页
paginate_path: "page:num"
